### PR TITLE
upgrade to 6.1 with raster stats and equal area

### PR DESCRIPTION
**Pull request by twelch**
I followed the 6.1 [migration guide](https://github.com/seasketch/geoprocessing/blob/dev/CHANGELOG.md) for this PR.  Some bugs were found, resulting in a 6.1.1 release.  @avmey, please review this PR to see what migration looks like, and to get a second set of eyes on the change in the smoke test results, looking for any additional anomalies.  If it looks good could you merge the PR and deploy it?

Main changes:
- `overlapRaster` calls have been migrated to `rasterMetrics`.  Each call is still calculating only a single stat on a single band raster, so it's not yet exercising it's full capability, but it works.
- I'm seeing a pretty big swing in calculated values for some of the OUS heatmaps for Azores for example santa-maria sketch example.  Rasters are now imported in the equal area projection, and the heatmap raster cell size stays about the same, as do the values by using nearest neighbor resampling, just the raster cells are shifted, as happens with raster reprojection.
What I'm seeing as a result with this shift in the grid is that 2 more pixels get included in the overlap analysis for this example, which more than doubles the heatmap value picked up.  As a result 3.1% can become 10.9%.

### CODE REVIEW

**Review by avmey — CHANGES_REQUESTED** [review]
Hitting precalc error:
```
Precalculating datasource saojorge_cultural_heritage_ous for geography pico
precalcing raster datasource http://127.0.0.1:8001/saojorge_cultural_heritage_ous.tif
overlapRaster geoblaze.stats threw, meaning no cells with value were found within the geometry
precalculated metrics are invalid, this is a bug with the precalc script
[
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "nan",
    "path": [
      1998,
      "value"
    ],
    "message": "Expected number, received nan"
  }
]
```

Error occurs when geoblaze.stats() throws in rasterStats, we catch the error and return default stats which look like `[ { valid: 0, count: 0, sum: 0, area: undefined } ]` instead of `[ { count: 0, sum: 0, area: 0 } ]` , (deleting `valid` and calculating `area` occur in the try code but not in the catch code). This creates metrics with `{"metricId": "valid", "value": 0}` and invalid metrics with `{"metricId": "area", "value": null}` which error during zod validation.

I'll start on a fix in the gp library.

**Comment by twelch** [comment]
@avmey interesting.  There are unit tests that I thought should cover this use case, probably in `rasterStats.test.ts`.  Consider looking to adapt the use case to make the fix.

**Comment by avmey** [comment]
@twelch Double checking, is there a situation where we would want to create metrics with `"metricId": "valid"`?

**Review by avmey — APPROVED** [review]

**Comment by avmey** [comment]
Everything looks correct to me. Agree that with large raster cell sizes we are seeing a big swing in some numbers. I think the trickiest part will be that the visualization in Overlay Layers can now "disagree" with the data we're using to calculate totals. 

Ex. in `overlap test collection`:
- The following is what the user will see, implying sketch2 has a value of 158:
Screenshot 2024-01-16 at 9 55 38 AM

- But sketch2 will instead return a value of 0 due to the reprojection:
Screenshot 2024-01-16 at 9 55 20 AM

**Pull request merged**
